/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ChatId = bigint;
export interface ChatSummary {
  'lastMessageText' : [] | [string],
  'lastMessageAt' : [] | [Timestamp],
  'partnerDisplayName' : string,
  'partnerId' : UserId,
  'unreadCount' : bigint,
  'chatId' : ChatId,
}
export interface IcebreakerPrompt { 'id' : bigint, 'text' : string }
export type Interest = { 'Art' : null } |
  { 'Food' : null } |
  { 'Tech' : null } |
  { 'Books' : null } |
  { 'Travel' : null } |
  { 'Gaming' : null } |
  { 'Music' : null } |
  { 'Sports' : null };
export type MessageId = bigint;
export interface MessagePublic {
  'id' : MessageId,
  'text' : string,
  'sentAt' : Timestamp,
  'chatId' : ChatId,
  'reactions' : Array<Reaction>,
  'senderId' : UserId,
  'readBy' : Array<UserId>,
}
export interface Reaction { 'userId' : UserId, 'emoji' : string }
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'displayName' : string,
  'interests' : Array<Interest>,
  'createdAt' : Timestamp,
}
export interface _SERVICE {
  'addReaction' : ActorMethod<[ChatId, MessageId, string], undefined>,
  'findNewMatch' : ActorMethod<[], [] | [ChatId]>,
  'getChatMessages' : ActorMethod<[ChatId], Array<MessagePublic>>,
  'getIcebreakerPrompt' : ActorMethod<[ChatId], IcebreakerPrompt>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getReactions' : ActorMethod<[ChatId, MessageId], Array<[string, bigint]>>,
  'listChats' : ActorMethod<[], Array<ChatSummary>>,
  'markMessagesRead' : ActorMethod<[ChatId], undefined>,
  'refreshIcebreakerPrompt' : ActorMethod<[ChatId, bigint], IcebreakerPrompt>,
  'registerUser' : ActorMethod<[string, Array<Interest>], UserProfilePublic>,
  'removeReaction' : ActorMethod<[ChatId, MessageId], undefined>,
  'sendMessage' : ActorMethod<[ChatId, string], MessagePublic>,
  'updateProfile' : ActorMethod<[string, Array<Interest>], UserProfilePublic>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];