/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChatId = IDL.Nat;
export const MessageId = IDL.Nat;
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const Reaction = IDL.Record({ 'userId' : UserId, 'emoji' : IDL.Text });
export const MessagePublic = IDL.Record({
  'id' : MessageId,
  'text' : IDL.Text,
  'sentAt' : Timestamp,
  'chatId' : ChatId,
  'reactions' : IDL.Vec(Reaction),
  'senderId' : UserId,
  'readBy' : IDL.Vec(UserId),
});
export const IcebreakerPrompt = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
});
export const Interest = IDL.Variant({
  'Art' : IDL.Null,
  'Food' : IDL.Null,
  'Tech' : IDL.Null,
  'Books' : IDL.Null,
  'Travel' : IDL.Null,
  'Gaming' : IDL.Null,
  'Music' : IDL.Null,
  'Sports' : IDL.Null,
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'displayName' : IDL.Text,
  'interests' : IDL.Vec(Interest),
  'createdAt' : Timestamp,
});
export const ChatSummary = IDL.Record({
  'lastMessageText' : IDL.Opt(IDL.Text),
  'lastMessageAt' : IDL.Opt(Timestamp),
  'partnerDisplayName' : IDL.Text,
  'partnerId' : UserId,
  'unreadCount' : IDL.Nat,
  'chatId' : ChatId,
});

export const idlService = IDL.Service({
  'addReaction' : IDL.Func([ChatId, MessageId, IDL.Text], [], []),
  'findNewMatch' : IDL.Func([], [IDL.Opt(ChatId)], []),
  'getChatMessages' : IDL.Func([ChatId], [IDL.Vec(MessagePublic)], ['query']),
  'getIcebreakerPrompt' : IDL.Func([ChatId], [IcebreakerPrompt], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
  'getReactions' : IDL.Func(
      [ChatId, MessageId],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'listChats' : IDL.Func([], [IDL.Vec(ChatSummary)], ['query']),
  'markMessagesRead' : IDL.Func([ChatId], [], []),
  'refreshIcebreakerPrompt' : IDL.Func(
      [ChatId, IDL.Nat],
      [IcebreakerPrompt],
      ['query'],
    ),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Vec(Interest)],
      [UserProfilePublic],
      [],
    ),
  'removeReaction' : IDL.Func([ChatId, MessageId], [], []),
  'sendMessage' : IDL.Func([ChatId, IDL.Text], [MessagePublic], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Vec(Interest)],
      [UserProfilePublic],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChatId = IDL.Nat;
  const MessageId = IDL.Nat;
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const Reaction = IDL.Record({ 'userId' : UserId, 'emoji' : IDL.Text });
  const MessagePublic = IDL.Record({
    'id' : MessageId,
    'text' : IDL.Text,
    'sentAt' : Timestamp,
    'chatId' : ChatId,
    'reactions' : IDL.Vec(Reaction),
    'senderId' : UserId,
    'readBy' : IDL.Vec(UserId),
  });
  const IcebreakerPrompt = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });
  const Interest = IDL.Variant({
    'Art' : IDL.Null,
    'Food' : IDL.Null,
    'Tech' : IDL.Null,
    'Books' : IDL.Null,
    'Travel' : IDL.Null,
    'Gaming' : IDL.Null,
    'Music' : IDL.Null,
    'Sports' : IDL.Null,
  });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'displayName' : IDL.Text,
    'interests' : IDL.Vec(Interest),
    'createdAt' : Timestamp,
  });
  const ChatSummary = IDL.Record({
    'lastMessageText' : IDL.Opt(IDL.Text),
    'lastMessageAt' : IDL.Opt(Timestamp),
    'partnerDisplayName' : IDL.Text,
    'partnerId' : UserId,
    'unreadCount' : IDL.Nat,
    'chatId' : ChatId,
  });
  
  return IDL.Service({
    'addReaction' : IDL.Func([ChatId, MessageId, IDL.Text], [], []),
    'findNewMatch' : IDL.Func([], [IDL.Opt(ChatId)], []),
    'getChatMessages' : IDL.Func([ChatId], [IDL.Vec(MessagePublic)], ['query']),
    'getIcebreakerPrompt' : IDL.Func([ChatId], [IcebreakerPrompt], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
    'getReactions' : IDL.Func(
        [ChatId, MessageId],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'listChats' : IDL.Func([], [IDL.Vec(ChatSummary)], ['query']),
    'markMessagesRead' : IDL.Func([ChatId], [], []),
    'refreshIcebreakerPrompt' : IDL.Func(
        [ChatId, IDL.Nat],
        [IcebreakerPrompt],
        ['query'],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Vec(Interest)],
        [UserProfilePublic],
        [],
      ),
    'removeReaction' : IDL.Func([ChatId, MessageId], [], []),
    'sendMessage' : IDL.Func([ChatId, IDL.Text], [MessagePublic], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Vec(Interest)],
        [UserProfilePublic],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };