/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface MessagePublic {
    id: MessageId;
    text: string;
    sentAt: Timestamp;
    chatId: ChatId;
    reactions: Array<Reaction>;
    senderId: UserId;
    readBy: Array<UserId>;
}
export interface IcebreakerPrompt {
    id: bigint;
    text: string;
}
export type MessageId = bigint;
export type ChatId = bigint;
export interface ChatSummary {
    lastMessageText?: string;
    lastMessageAt?: Timestamp;
    partnerDisplayName: string;
    partnerId: UserId;
    unreadCount: bigint;
    chatId: ChatId;
}
export interface UserProfilePublic {
    id: UserId;
    displayName: string;
    interests: Array<Interest>;
    createdAt: Timestamp;
}
export interface Reaction {
    userId: UserId;
    emoji: string;
}
export enum Interest {
    Art = "Art",
    Food = "Food",
    Tech = "Tech",
    Books = "Books",
    Travel = "Travel",
    Gaming = "Gaming",
    Music = "Music",
    Sports = "Sports"
}
export interface backendInterface {
    addReaction(chatId: ChatId, messageId: MessageId, emoji: string): Promise<void>;
    findNewMatch(): Promise<ChatId | null>;
    getChatMessages(chatId: ChatId): Promise<Array<MessagePublic>>;
    getIcebreakerPrompt(chatId: ChatId): Promise<IcebreakerPrompt>;
    getMyProfile(): Promise<UserProfilePublic | null>;
    getReactions(chatId: ChatId, messageId: MessageId): Promise<Array<[string, bigint]>>;
    listChats(): Promise<Array<ChatSummary>>;
    markMessagesRead(chatId: ChatId): Promise<void>;
    refreshIcebreakerPrompt(chatId: ChatId, currentPromptId: bigint): Promise<IcebreakerPrompt>;
    registerUser(displayName: string, interests: Array<Interest>): Promise<UserProfilePublic>;
    removeReaction(chatId: ChatId, messageId: MessageId): Promise<void>;
    sendMessage(chatId: ChatId, text: string): Promise<MessagePublic>;
    updateProfile(displayName: string, interests: Array<Interest>): Promise<UserProfilePublic>;
}
import type { ChatId as _ChatId, ChatSummary as _ChatSummary, Interest as _Interest, Timestamp as _Timestamp, UserId as _UserId, UserProfilePublic as _UserProfilePublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addReaction(arg0: ChatId, arg1: MessageId, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReaction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReaction(arg0, arg1, arg2);
            return result;
        }
    }
    async findNewMatch(): Promise<ChatId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.findNewMatch();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findNewMatch();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatMessages(arg0: ChatId): Promise<Array<MessagePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatMessages(arg0);
            return result;
        }
    }
    async getIcebreakerPrompt(arg0: ChatId): Promise<IcebreakerPrompt> {
        if (this.processError) {
            try {
                const result = await this.actor.getIcebreakerPrompt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIcebreakerPrompt(arg0);
            return result;
        }
    }
    async getMyProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReactions(arg0: ChatId, arg1: MessageId): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReactions(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReactions(arg0, arg1);
            return result;
        }
    }
    async listChats(): Promise<Array<ChatSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChats();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChats();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async markMessagesRead(arg0: ChatId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessagesRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessagesRead(arg0);
            return result;
        }
    }
    async refreshIcebreakerPrompt(arg0: ChatId, arg1: bigint): Promise<IcebreakerPrompt> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshIcebreakerPrompt(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshIcebreakerPrompt(arg0, arg1);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: Array<Interest>): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, to_candid_vec_n13(this._uploadFile, this._downloadFile, arg1));
                return from_candid_UserProfilePublic_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, to_candid_vec_n13(this._uploadFile, this._downloadFile, arg1));
            return from_candid_UserProfilePublic_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeReaction(arg0: ChatId, arg1: MessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeReaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeReaction(arg0, arg1);
            return result;
        }
    }
    async sendMessage(arg0: ChatId, arg1: string): Promise<MessagePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: Array<Interest>): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, to_candid_vec_n13(this._uploadFile, this._downloadFile, arg1));
                return from_candid_UserProfilePublic_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, to_candid_vec_n13(this._uploadFile, this._downloadFile, arg1));
            return from_candid_UserProfilePublic_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ChatSummary_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatSummary): ChatSummary {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Interest_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Interest): Interest {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChatId]): ChatId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastMessageText: [] | [string];
    lastMessageAt: [] | [_Timestamp];
    partnerDisplayName: string;
    partnerId: _UserId;
    unreadCount: bigint;
    chatId: _ChatId;
}): {
    lastMessageText?: string;
    lastMessageAt?: Timestamp;
    partnerDisplayName: string;
    partnerId: UserId;
    unreadCount: bigint;
    chatId: ChatId;
} {
    return {
        lastMessageText: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.lastMessageText)),
        lastMessageAt: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.lastMessageAt)),
        partnerDisplayName: value.partnerDisplayName,
        partnerId: value.partnerId,
        unreadCount: value.unreadCount,
        chatId: value.chatId
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    displayName: string;
    interests: Array<_Interest>;
    createdAt: _Timestamp;
}): {
    id: UserId;
    displayName: string;
    interests: Array<Interest>;
    createdAt: Timestamp;
} {
    return {
        id: value.id,
        displayName: value.displayName,
        interests: from_candid_vec_n5(_uploadFile, _downloadFile, value.interests),
        createdAt: value.createdAt
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Art: null;
} | {
    Food: null;
} | {
    Tech: null;
} | {
    Books: null;
} | {
    Travel: null;
} | {
    Gaming: null;
} | {
    Music: null;
} | {
    Sports: null;
}): Interest {
    return "Art" in value ? Interest.Art : "Food" in value ? Interest.Food : "Tech" in value ? Interest.Tech : "Books" in value ? Interest.Books : "Travel" in value ? Interest.Travel : "Gaming" in value ? Interest.Gaming : "Music" in value ? Interest.Music : "Sports" in value ? Interest.Sports : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Interest>): Array<Interest> {
    return value.map((x)=>from_candid_Interest_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatSummary>): Array<ChatSummary> {
    return value.map((x)=>from_candid_ChatSummary_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Interest_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Interest): _Interest {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Interest): {
    Art: null;
} | {
    Food: null;
} | {
    Tech: null;
} | {
    Books: null;
} | {
    Travel: null;
} | {
    Gaming: null;
} | {
    Music: null;
} | {
    Sports: null;
} {
    return value == Interest.Art ? {
        Art: null
    } : value == Interest.Food ? {
        Food: null
    } : value == Interest.Tech ? {
        Tech: null
    } : value == Interest.Books ? {
        Books: null
    } : value == Interest.Travel ? {
        Travel: null
    } : value == Interest.Gaming ? {
        Gaming: null
    } : value == Interest.Music ? {
        Music: null
    } : value == Interest.Sports ? {
        Sports: null
    } : value;
}
function to_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Interest>): Array<_Interest> {
    return value.map((x)=>to_candid_Interest_n14(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
